steps:

  # Substitute the version
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args: ["-c", "sed -i 's/%VERSION%/'$TAG_NAME'/g' setup.cfg"]
    
  # Install dependencies
  - name: python:3.9-buster
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Run unit tests
  - name: python:3.9-buster
    entrypoint: python
    args: ["-m", "tox"]

  # Capture results
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args: ["-c", "cp coverage/junit.xml ${SHORT_SHA}_test_log.xml"]

  # Publish results
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
    - '-c'
    - |
        if [ $PROJECT_ID == "alexei-dev" ]
        then
          echo "${_LOG_BUCKET_DEV}" > log_bucket
        fi

        if [ $PROJECT_ID == "alexei-qa" ]
        then
          echo "${_LOG_BUCKET_QA}" > log_bucket
        fi

        if [ $PROJECT_ID == "alexei-prod" ]
        then
          echo "${_LOG_BUCKET_PROD}" > log_bucket
        fi

        echo "Establishing test results..."
        echo ${SHORT_SHA}_test_log.xml

        echo "Establishing logs bucket..."
        _LOG_BUCKET=$(cat log_bucket)
        echo "$${_LOG_BUCKET}"

        echo "Publishing test results..."
        gsutil cp ${SHORT_SHA}_test_log.xml gs://$${_LOG_BUCKET}

substitutions:
  _LOG_BUCKET_DEV: logs-hmjbvyp8eqyefrh
  _LOG_BUCKET_QA: logs-j4tztbeljefbpvo
  _LOG_BUCKET_PROD: logs-nfrjp2w3vyrt9xp
